@extends('admin.layouts.app')

@section('page-title', 'Inventory Report')
@section('page-subtitle', 'Stock valuation, low-stock exposure and outbound product movement.')

@section('content')
    <div class="space-y-6">
        <nav class="flex items-center gap-3 text-sm text-slate-400"><a href="{{ route('admin.dashboard') }}" class="hover:text-white">Admin</a><span>/</span><a href="{{ route('admin.reports.index') }}" class="hover:text-white">Reports</a><span>/</span><span class="text-white">Inventory</span></nav>
        <div class="flex gap-3"><a href="{{ route('admin.reports.export.pdf', ['type' => 'inventory']) }}" class="rounded-2xl border border-white/10 px-5 py-3 text-sm font-medium text-slate-200 transition hover:bg-white/10">PDF</a><a href="{{ route('admin.reports.export.excel', ['type' => 'inventory']) }}" class="rounded-2xl border border-white/10 px-5 py-3 text-sm font-medium text-slate-200 transition hover:bg-white/10">CSV</a></div>
        <div class="grid gap-4 md:grid-cols-2"><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Stock Value</p><p class="mt-3 text-3xl font-semibold text-white">{{ number_format((float) $totalValue, 2) }}</p></div><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-emerald-300">Retail Value Proxy</p><p class="mt-3 text-3xl font-semibold text-white">{{ number_format((float) $totalRetailValue, 2) }}</p></div></div>
        <div class="grid gap-6 xl:grid-cols-2"><section class="rounded-3xl border border-white/10 bg-slate-950/50 p-6"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Low Stock Items</p><div class="mt-6 overflow-x-auto"><table class="min-w-full divide-y divide-white/10 text-left text-sm text-slate-300"><thead class="text-xs uppercase tracking-[0.25em] text-slate-500"><tr><th class="px-4 py-3">Product</th><th class="px-4 py-3">Stock</th><th class="px-4 py-3">Reorder</th></tr></thead><tbody class="divide-y divide-white/5">@forelse ($lowStock as $product)<tr><td class="px-4 py-4 text-white">{{ $product->name }}</td><td class="px-4 py-4">{{ $product->stock_on_hand }}</td><td class="px-4 py-4">{{ $product->reorder_level }}</td></tr>@empty<tr><td colspan="3" class="px-4 py-10 text-center text-slate-400">No low-stock items found.</td></tr>@endforelse</tbody></table></div></section><section class="rounded-3xl border border-white/10 bg-slate-950/50 p-6"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Top Sellers</p><div class="mt-6 space-y-3">@forelse ($topSellers as $row)<div class="flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 px-4 py-3"><span class="text-slate-200">{{ $row->name }}</span><span class="font-medium text-white">{{ number_format((float) $row->total_sold, 2) }}</span></div>@empty<p class="text-sm text-slate-400">No outbound stock movements recorded yet.</p>@endforelse</div></section></div>
    </div>
@endsection
