@extends('admin.layouts.app')

@section('page-title', 'Sales Report')
@section('page-subtitle', 'Invoice performance, customer concentration and billing trend for the selected period.')

@section('content')
    <div class="space-y-6">
        <nav class="flex items-center gap-3 text-sm text-slate-400"><a href="{{ route('admin.dashboard') }}" class="hover:text-white">Admin</a><span>/</span><a href="{{ route('admin.reports.index') }}" class="hover:text-white">Reports</a><span>/</span><span class="text-white">Sales</span></nav>
        <form method="GET" action="{{ route('admin.reports.sales') }}" class="grid gap-4 rounded-3xl border border-white/10 bg-slate-950/50 p-6 md:grid-cols-[1fr_1fr_auto]"><label class="block text-sm text-slate-300">Start Date<input type="date" name="start_date" value="{{ $startDate }}" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white"></label><label class="block text-sm text-slate-300">End Date<input type="date" name="end_date" value="{{ $endDate }}" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white"></label><div class="flex items-end gap-3"><button class="rounded-2xl border border-cyan-400/30 bg-cyan-400/10 px-5 py-3 text-sm font-medium text-cyan-100 transition hover:bg-cyan-400/20">Run report</button><a href="{{ route('admin.reports.export.pdf', ['type' => 'sales', 'start_date' => $startDate, 'end_date' => $endDate]) }}" class="rounded-2xl border border-white/10 px-5 py-3 text-sm font-medium text-slate-200 transition hover:bg-white/10">PDF</a><a href="{{ route('admin.reports.export.excel', ['type' => 'sales', 'start_date' => $startDate, 'end_date' => $endDate]) }}" class="rounded-2xl border border-white/10 px-5 py-3 text-sm font-medium text-slate-200 transition hover:bg-white/10">CSV</a></div></form>
        <div class="grid gap-4 md:grid-cols-3"><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Total Sales</p><p class="mt-3 text-3xl font-semibold text-white">{{ number_format((float) $totalSales, 2) }}</p></div><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-emerald-300">Invoices</p><p class="mt-3 text-3xl font-semibold text-white">{{ $totalInvoices }}</p></div><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-amber-300">Average Order</p><p class="mt-3 text-3xl font-semibold text-white">{{ number_format((float) $averageOrderValue, 2) }}</p></div></div>
        <div class="grid gap-6 xl:grid-cols-2"><section class="rounded-3xl border border-white/10 bg-slate-950/50 p-6"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Top Customers</p><div class="mt-6 space-y-3">@forelse ($topCustomers as $customer)<div class="flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 px-4 py-3"><span class="text-slate-200">{{ $customer->name }}</span><span class="font-medium text-white">{{ number_format((float) ($customer->total_spent ?? 0), 2) }}</span></div>@empty<p class="text-sm text-slate-400">No customer sales data for the selected period.</p>@endforelse</div></section><section class="rounded-3xl border border-white/10 bg-slate-950/50 p-6"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Daily Sales Trend</p><div class="mt-6 space-y-3">@forelse ($dailySales as $row)<div class="flex items-center justify-between rounded-2xl border border-white/10 bg-white/5 px-4 py-3"><span class="text-slate-200">{{ $row->report_date }}</span><span class="font-medium text-white">{{ $row->invoice_count }} / {{ number_format((float) $row->total, 2) }}</span></div>@empty<p class="text-sm text-slate-400">No invoice activity in the selected period.</p>@endforelse</div></section></div>
    </div>
@endsection
