@extends('admin.layouts.app')

@section('page-title', 'Sales Invoices')
@section('page-subtitle', 'Issue customer invoices from sales activity and track billing status.')

@section('content')
    <div class="space-y-6">
        <nav class="flex items-center gap-3 text-sm text-slate-400"><a href="{{ route('admin.dashboard') }}" class="hover:text-white">Admin</a><span>/</span><span>Operations</span><span>/</span><span class="text-white">Sales Invoices</span></nav>
        @if (session('status'))<div class="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-100">{{ session('status') }}</div>@endif
        <div class="grid gap-4 md:grid-cols-4"><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Invoices</p><p class="mt-3 text-3xl font-semibold text-white">{{ $summary['count'] }}</p></div><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-emerald-300">Sent</p><p class="mt-3 text-3xl font-semibold text-white">{{ $summary['sent'] }}</p></div><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-amber-300">Paid</p><p class="mt-3 text-3xl font-semibold text-white">{{ $summary['paid'] }}</p></div><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-fuchsia-300">Value</p><p class="mt-3 text-3xl font-semibold text-white">{{ number_format((float) $summary['value'], 2) }}</p></div></div>
        <div class="grid gap-6 xl:grid-cols-[1fr_1.25fr]">
            <section class="rounded-3xl border border-white/10 bg-white/6 p-6 shadow-2xl shadow-slate-950/30 backdrop-blur"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Create Sales Invoice</p><form method="POST" action="{{ route('admin.sales.invoices.store') }}" class="mt-6 space-y-4">@csrf<div class="grid gap-4 md:grid-cols-2"><label class="block text-sm text-slate-300">Invoice Number<input name="invoice_number" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white" required></label><label class="block text-sm text-slate-300">Customer<select name="customer_id" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white" required><option value="">Select customer</option>@foreach ($customers as $customer)<option value="{{ $customer->id }}">{{ $customer->customer_code }} | {{ $customer->name }}</option>@endforeach</select></label><label class="block text-sm text-slate-300">Quotation<select name="quotation_id" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white"><option value="">Optional quotation</option>@foreach ($quotations as $quotation)<option value="{{ $quotation->id }}">{{ $quotation->quotation_number }}</option>@endforeach</select></label><label class="block text-sm text-slate-300">Status<select name="status" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white"><option value="draft">Draft</option><option value="sent">Sent</option><option value="paid">Paid</option><option value="cancelled">Cancelled</option></select></label><label class="block text-sm text-slate-300">Issue Date<input type="date" name="issue_date" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white" required></label><label class="block text-sm text-slate-300">Due Date<input type="date" name="due_date" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white" required></label><label class="block text-sm text-slate-300 md:col-span-2">Total Amount<input type="number" step="0.01" min="0" name="total_amount" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white" required></label></div><label class="block text-sm text-slate-300">Notes<textarea name="notes" rows="4" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white"></textarea></label><button class="rounded-2xl border border-cyan-400/30 bg-cyan-400/10 px-5 py-3 text-sm font-medium text-cyan-100 transition hover:bg-cyan-400/20">Save sales invoice</button></form></section>
            <section class="rounded-3xl border border-white/10 bg-slate-950/50 p-6 shadow-2xl shadow-slate-950/30"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Sales Invoice Register</p><div class="mt-6 overflow-x-auto"><table class="min-w-full divide-y divide-white/10 text-left text-sm text-slate-300"><thead class="text-xs uppercase tracking-[0.25em] text-slate-500"><tr><th class="px-4 py-3">Invoice</th><th class="px-4 py-3">Customer</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Amount</th></tr></thead><tbody class="divide-y divide-white/5">@forelse ($invoices as $invoice)<tr><td class="px-4 py-4"><p class="font-medium text-white">{{ $invoice->invoice_number }}</p><p class="mt-1 text-xs text-slate-500">Due {{ optional($invoice->due_date)->format('d M Y') ?: 'Pending' }}</p></td><td class="px-4 py-4"><p>{{ $invoice->customer?->name ?: 'Unknown customer' }}</p><p class="mt-1 text-xs text-slate-500">{{ $invoice->quotation?->quotation_number ?: 'No quotation linked' }}</p></td><td class="px-4 py-4">{{ ucfirst($invoice->status) }}</td><td class="px-4 py-4">{{ number_format((float) $invoice->total_amount, 2) }}</td></tr>@empty<tr><td colspan="4" class="px-4 py-10 text-center text-slate-400">No sales invoices have been created yet.</td></tr>@endforelse</tbody></table></div></section>
        </div>
    </div>
@endsection
