@extends('admin.layouts.app')

@section('page-title', 'Receipts')
@section('page-subtitle', 'Capture customer payments received against issued sales invoices.')

@section('content')
    <div class="space-y-6">
        <nav class="flex items-center gap-3 text-sm text-slate-400"><a href="{{ route('admin.dashboard') }}" class="hover:text-white">Admin</a><span>/</span><span>Operations</span><span>/</span><span class="text-white">Receipts</span></nav>
        @if (session('status'))<div class="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-100">{{ session('status') }}</div>@endif
        <div class="grid gap-4 md:grid-cols-3"><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Receipts</p><p class="mt-3 text-3xl font-semibold text-white">{{ $summary['count'] }}</p></div><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-emerald-300">Received</p><p class="mt-3 text-3xl font-semibold text-white">{{ $summary['received'] }}</p></div><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-fuchsia-300">Value</p><p class="mt-3 text-3xl font-semibold text-white">{{ number_format((float) $summary['total'], 2) }}</p></div></div>
        <div class="grid gap-6 xl:grid-cols-[1fr_1.25fr]">
            <section class="rounded-3xl border border-white/10 bg-white/6 p-6 shadow-2xl shadow-slate-950/30 backdrop-blur"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Record Receipt</p><form method="POST" action="{{ route('admin.sales.receipts.store') }}" class="mt-6 space-y-4">@csrf<div class="grid gap-4 md:grid-cols-2"><label class="block text-sm text-slate-300">Receipt Number<input name="receipt_number" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white" required></label><label class="block text-sm text-slate-300">Sales Invoice<select name="sales_invoice_id" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white" required><option value="">Select invoice</option>@foreach ($salesInvoices as $invoice)<option value="{{ $invoice->id }}">{{ $invoice->invoice_number }} | {{ number_format((float) $invoice->total_amount, 2) }}</option>@endforeach</select></label><label class="block text-sm text-slate-300">Receipt Date<input type="date" name="receipt_date" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white" required></label><label class="block text-sm text-slate-300">Amount<input type="number" step="0.01" min="0" name="amount" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white" required></label><label class="block text-sm text-slate-300">Payment Method<select name="payment_method" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white"><option value="bank_transfer">Bank Transfer</option><option value="cash">Cash</option><option value="mobile_money">Mobile Money</option><option value="cheque">Cheque</option></select></label><label class="block text-sm text-slate-300">Status<select name="status" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white"><option value="received">Received</option><option value="pending">Pending</option><option value="reversed">Reversed</option></select></label></div><label class="block text-sm text-slate-300">Notes<textarea name="notes" rows="4" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white"></textarea></label><button class="rounded-2xl border border-cyan-400/30 bg-cyan-400/10 px-5 py-3 text-sm font-medium text-cyan-100 transition hover:bg-cyan-400/20">Save receipt</button></form></section>
            <section class="rounded-3xl border border-white/10 bg-slate-950/50 p-6 shadow-2xl shadow-slate-950/30"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Receipt Register</p><div class="mt-6 overflow-x-auto"><table class="min-w-full divide-y divide-white/10 text-left text-sm text-slate-300"><thead class="text-xs uppercase tracking-[0.25em] text-slate-500"><tr><th class="px-4 py-3">Receipt</th><th class="px-4 py-3">Invoice</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Amount</th></tr></thead><tbody class="divide-y divide-white/5">@forelse ($receipts as $receipt)<tr><td class="px-4 py-4"><p class="font-medium text-white">{{ $receipt->receipt_number }}</p><p class="mt-1 text-xs text-slate-500">{{ optional($receipt->receipt_date)->format('d M Y') ?: 'Pending' }}</p></td><td class="px-4 py-4">{{ $receipt->salesInvoice?->invoice_number ?: 'Unlinked' }}</td><td class="px-4 py-4">{{ ucfirst($receipt->status) }}</td><td class="px-4 py-4">{{ number_format((float) $receipt->amount, 2) }}</td></tr>@empty<tr><td colspan="4" class="px-4 py-10 text-center text-slate-400">No receipts have been recorded yet.</td></tr>@endforelse</tbody></table></div></section>
        </div>
    </div>
@endsection
