@extends('admin.layouts.app')

@section('page-title', 'Categories')
@section('page-subtitle', 'Organize product families and catalog structure for inventory control.')

@section('content')
    <div class="space-y-6">
        <nav class="flex items-center gap-3 text-sm text-slate-400"><a href="{{ route('admin.dashboard') }}" class="hover:text-white">Admin</a><span>/</span><span>Operations</span><span>/</span><span class="text-white">Categories</span></nav>
        @if (session('status'))<div class="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm text-emerald-100">{{ session('status') }}</div>@endif
        <div class="grid gap-4 md:grid-cols-2"><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Categories</p><p class="mt-3 text-3xl font-semibold text-white">{{ $summary['count'] }}</p></div><div class="rounded-3xl border border-white/10 bg-slate-950/50 p-5"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-emerald-300">Active</p><p class="mt-3 text-3xl font-semibold text-white">{{ $summary['active'] }}</p></div></div>
        <div class="grid gap-6 xl:grid-cols-[1fr_1.25fr]"><section class="rounded-3xl border border-white/10 bg-white/6 p-6 shadow-2xl shadow-slate-950/30 backdrop-blur"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Create Category</p><form method="POST" action="{{ route('admin.inventory.categories.store') }}" class="mt-6 space-y-4">@csrf<label class="block text-sm text-slate-300">Code<input name="code" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white" required></label><label class="block text-sm text-slate-300">Name<input name="name" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white" required></label><label class="block text-sm text-slate-300">Description<textarea name="description" rows="4" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white"></textarea></label><label class="block text-sm text-slate-300">Status<select name="is_active" class="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950/60 px-4 py-3 text-white"><option value="1">Active</option><option value="0">Inactive</option></select></label><button class="rounded-2xl border border-cyan-400/30 bg-cyan-400/10 px-5 py-3 text-sm font-medium text-cyan-100 transition hover:bg-cyan-400/20">Save category</button></form></section><section class="rounded-3xl border border-white/10 bg-slate-950/50 p-6 shadow-2xl shadow-slate-950/30"><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Category Register</p><div class="mt-6 overflow-x-auto"><table class="min-w-full divide-y divide-white/10 text-left text-sm text-slate-300"><thead class="text-xs uppercase tracking-[0.25em] text-slate-500"><tr><th class="px-4 py-3">Category</th><th class="px-4 py-3">Description</th><th class="px-4 py-3">Status</th></tr></thead><tbody class="divide-y divide-white/5">@forelse ($categories as $category)<tr><td class="px-4 py-4"><p class="font-medium text-white">{{ $category->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $category->code }}</p></td><td class="px-4 py-4">{{ $category->description ?: 'No description' }}</td><td class="px-4 py-4">{{ $category->is_active ? 'Active' : 'Inactive' }}</td></tr>@empty<tr><td colspan="3" class="px-4 py-10 text-center text-slate-400">No categories have been created yet.</td></tr>@endforelse</tbody></table></div></section></div>
    </div>
@endsection
